In [1]:
import numpy as np


In [2]:
arr = np.array([1,2,3,4])

In [3]:
print(type(arr))

<class 'numpy.ndarray'>


In [4]:
print(type(arr[1]))

<class 'numpy.int64'>


In [5]:
arr_2 = np.array([[1,2,3], [4,5,6]])

In [6]:
print(arr_2)

[[1 2 3]
 [4 5 6]]


In [7]:
arr_3 = np.array([1,2,3, "hello"])
print(type(arr_3[1]))

<class 'numpy.str_'>


In [8]:
arr_6 = np.array([1,2,3, "10"], dtype=np.float16)

In [11]:
print(type(arr_6[1]))
print(arr_6)

<class 'numpy.float16'>
[ 1.  2.  3. 10.]


In [13]:
arr_11 = np.arange(4,10,2)
print(arr_11)

[4 6 8]


In [14]:
arr_12 = np.linspace(1,100,10)
print(arr_12)

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


In [18]:
for num in np.linspace(1,10,10,dtype=np.int8):
    print(num)
for num in np.linspace(1,10,10,dtype=np.float16):
    print(num)

1
2
3
4
5
6
7
8
9
10
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0


In [25]:
zero_np = np.zeros((5,5), dtype=np.float16)
print(zero_np)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [28]:
np_zeros = np.ones((4,5,6,2))
print(np_zeros)

[[[[1. 1.]
   [1. 1.]
   [1. 1.]
   [1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]
   [1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]
   [1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]
   [1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]
   [1. 1.]
   [1. 1.]
   [1. 1.]]]


 [[[1. 1.]
   [1. 1.]
   [1. 1.]
   [1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]
   [1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]
   [1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]
   [1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]
   [1. 1.]
   [1. 1.]
   [1. 1.]]]


 [[[1. 1.]
   [1. 1.]
   [1. 1.]
   [1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]
   [1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]
   [1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]
   [1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]
   [1. 1.]


In [31]:
arr = np.arange(0,10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
arr = np.arange()

In [39]:
arr=np.empty((3,3))
arrr = np.full((4,4,4),5)
print(arrr)

[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]

 [[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]

 [[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]

 [[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]]


In [40]:
arr = np.arange(0,10)
print(arr)
print(arr.ndim)

[0 1 2 3 4 5 6 7 8 9]
1


In [42]:
arr = np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [44]:
arr = np.linspace(1,101,10)
print(arr)

[  1.          12.11111111  23.22222222  34.33333333  45.44444444
  56.55555556  67.66666667  78.77777778  89.88888889 101.        ]


In [47]:
arr= np.random.rand(2,11)
print(arr)

[[0.92332579 0.5496515  0.3873759  0.12494832 0.62059391 0.22415326
  0.58296483 0.23997453 0.36940904 0.6560354  0.58150299]
 [0.36848574 0.74119704 0.06566828 0.49018969 0.9485812  0.43033728
  0.59626218 0.12516142 0.93142074 0.59392575 0.64355421]]
