In [2]:
import numpy as np

In [3]:
a_list = [1,2,3]
b_list = [4,5,6]

#this operation concatenate list

print(a_list + b_list)

[1, 2, 3, 4, 5, 6]


In [4]:
a = np.array([1,2,3])
b = np.array([4,5,6])

#this operation sum element wise

print(a+b)

[5 7 9]


In [5]:
print(a*b)

[ 4 10 18]


In [6]:
print(np.dot(a,b))

32


In [7]:
a_1 = np.array([[1,2,3],[4,5,6]])
b_1 = np.array([[1,2,3],[4,5,6]])

In [8]:
print(a_1.shape)
print(b_1.shape)

(2, 3)
(2, 3)


In [9]:
print(b_1.T)
print(b_1.T.shape)

[[1 4]
 [2 5]
 [3 6]]
(3, 2)


In [10]:
print(np.dot(a_1,b_1.T))

[[14 32]
 [32 77]]


In [11]:
a_1@b_1.T

array([[14, 32],
       [32, 77]])

In [12]:
# apple, banana, smartphone, toy, furniture
shop_sold_amazon = np.array([
    [100, 200, 20, 30, 5], # state-1-product-sold
    [200, 400, 40, 60, 10] # state-2-product-sold
])
print(shop_sold_amazon.shape)

(2, 5)


In [13]:
price_amazon = np.array([
    [30, 10, 1000, 10, 200], # state-1-price
    [34, 12, 1100, 11, 220] # state-2-price
])
print(price_amazon.shape)

(2, 5)


In [14]:
print(f"Revenue: {shop_sold_amazon@price_amazon.T}")
revenue_mat = shop_sold_amazon@price_amazon.T

Revenue: [[26300 29230]
 [52600 58460]]


In [15]:
print(revenue_mat.shape)

(2, 2)


In [16]:
dig = np.eye(2)
print(dig)

[[1. 0.]
 [0. 1.]]


In [17]:
print(np.sum(revenue_mat@dig))

166590.0


In [18]:
np.sum(revenue_mat*np.eye(2))

np.float64(84760.0)

In [19]:
revenue_mat.trace()

np.int64(84760)

In [20]:
arr = shop_sold_amazon.flatten()

In [21]:
arr

array([100, 200,  20,  30,   5, 200, 400,  40,  60,  10])

In [22]:
print("Sorted:", np.sort(arr))
print("Sorted indices:", np.argsort(arr))
# Instead of returning the sorted values themselves, 
# it returns an array of indices that, when used to index the original array, would produce a sorted sequence.

Sorted: [  5  10  20  30  40  60 100 200 200 400]
Sorted indices: [4 9 2 3 7 8 0 1 5 6]


In [23]:
print(len(arr))

10


In [24]:
print("Insert 4 position:", np.searchsorted(np.sort(arr), 4))
print("Unique elements:", np.unique(arr))
print("Count of each element:", np.bincount(arr)) # MIN - 0 , maX - 8

# 0,1,2,3,4,5,6,7,8
# 0,4,1....

Insert 4 position: 0
Unique elements: [  5  10  20  30  40  60 100 200 400]
Count of each element: [0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0
 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]


In [26]:
a = np.array(['hello', 'world'])
b = np.array(['_user', '_123'])

np.char.title(a)

array(['Hello', 'World'], dtype='<U5')

In [30]:
np.char.swapcase(a)
np.char.center(a,100,fillchar="=")

array(['===============================================hello================================================',
       '===============================================world================================================'],
      dtype='<U100')

In [38]:
def password(value):
    p=np.array([value[-4:]])
    print(np.char.center(value,10,fillchar="X"))

In [31]:
print(arr)

[100 200  20  30   5 200 400  40  60  10]


In [32]:
arr[-4:]

array([400,  40,  60,  10])

In [39]:
password("sameer")

XXsameerXX


In [40]:
!pip install pandas

'pip' is not recognized as an internal or external command,
operable program or batch file.


In [41]:
import pandas as pd

In [42]:
url = titanic_dataset_github_url = "https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv"


In [43]:
df = pd.read_csv(url)

In [45]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S


In [46]:
df["Name"]

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...                        
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

In [47]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [58]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    str    
 4   Sex          891 non-null    str    
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    str    
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str    
 11  Embarked     889 non-null    str    
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB


In [48]:
df[["Name","Age","Parch"]]

,Name,Age,Parch
0,"Braund, Mr. Owen Harris",22.0,0
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,0
2,"Heikkinen, Miss. Laina",26.0,0
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,0
4,"Allen, Mr. William Henry",35.0,0
...,...,...,...
886,"Montvila, Rev. Juozas",27.0,0
887,"Graham, Miss. Margaret Edith",19.0,0
888,"Johnston, Miss. Catherine Helen ""Carrie""",NaN,2
889,"Behr, Mr. Karl Howell",26.0,0


In [57]:
df.groupby('Sex')["Ticket"].mean()

TypeError: dtype 'str' does not support operation 'mean'