In [7]:
import numpy as np
a = np.array([[1, 2], [3, 4], [52,23]])
print(np.shape(a))

(3, 2)


In [9]:
print(np.ravel(a))
print(np.shape(a))
print(a.ravel())

[ 1  2  3  4 52 23]
(3, 2)
[ 1  2  3  4 52 23]


In [12]:
b=np.array([[1, 2], [3, 4], [52,23]])
b_ravel = b.ravel()
print(id(b))
print(id(b_ravel))
print(id(np.ravel(b)))

2746567208240
2746567209488
2746567208912


In [15]:
print(b.__array_interface__["data"][0])
print(b.ravel().__array_interface__["data"][0])

2746096404256
2746096404256


In [16]:
b=np.array([[1, 2], [3, 4], [52,23]])
b_ravel = b.ravel()
print(id(b))
print(id(b_ravel))
print(id(np.ravel(b)))

2746567608528
2746567608048
2746567618704


In [20]:
a[1][0] = 110

In [21]:
print(a)

[[  1   2]
 [110  10]
 [ 52  23]]


In [22]:
print(a.ravel())

[  1   2 110  10  52  23]


In [27]:
mat = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(mat)
print(mat[::-1,::-1])
print(mat.transpose())
print(mat.trace())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
15


In [30]:
arr = np.array([10, 15, 20, 25, 30])
idx = np.where(arr==30)
print(idx)
print(arr[idx])

(array([4]),)
[30]


In [2]:
import numpy as np

In [12]:
arr =np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9],
                [2,3,4]])
flat_arr = arr.flatten()

In [7]:
print(arr)
print(flat_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [13]:
print(id(arr))
print(id(flat_arr))

1794207574576
1793834367472


In [16]:
re_arr = flat_arr.reshape(2,2,3)
print(re_arr)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [2 3 4]]]


In [17]:
sq = arr.squeeze()
print(sq)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [2 3 4]]


In [18]:
mat = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

In [19]:
mat[::,1]

array([2, 5, 8])

In [21]:
print(mat[mat>6])
print(mat>7)

[7 8 9]
[[False False False]
 [False False False]
 [False  True  True]]
